CREATE DATABASE IF NOT EXISTS Score;
USE Score;

CREATE TABLE IF NOT EXISTS score (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tiempo VARCHAR(50) NOT NULL,
  puntos INT NOT NULL,
  fecha DATETIME NOT NULL,
  nombre VARCHAR(120) NOT NULL
);
